name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Clone raylib
      run: git clone https://github.com/raysan5/raylib.git
      
    - name: apt update
      run: sudo apt-get update
    
    - name: Install dependencies
      run: sudo apt install libasound2-dev mesa-common-dev libx11-dev libxrandr-dev libxi-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev
    
    - name: Build and install raylib
      run: cd raylib/src/ && make PLATFORM=PLATFORM_DESKTOP && sudo make install 
      
    - name: Build snake (run make)
      run: make
